### ISSUE TITLE
read_tiff error

### ISSUE THREAD

**Issue by XYangXRay** [conda-forge/dxchange-feedstock#4]
I updated dxchange with conda-forge, and got the following error when read the 3D tiff file:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-39-f081ce4055ba> in <module>()
      1 ifp_path = '/gpfs/petra3/scratch/yangx/phase_data/data67_processed.tiff'
----> 2 ifp_test = dxchange.read_tiff(ifp_path)
      3 print ifp_test.shape

/home/yangx/anaconda2/lib/python2.7/site-packages/dxchange/reader.pyc in read_tiff(fname, slc)
    139     fname = _check_read(fname)
    140     try:
--> 141         arr = tifffile.imread(fname, out='memmap')
    142     except IOError:
    143         logger.error('No such file or directory: %s', fname)

/home/yangx/anaconda2/lib/python2.7/site-packages/tifffile/tifffile.pyc in imread(files, **kwargs)
   1113     if isinstance(files, basestring):
   1114         with TiffFile(files, **kwargs_file) as tif:
-> 1115             return tif.asarray(**kwargs)
   1116     else:
   1117         with TiffSequence(files, **kwargs_seq) as imseq:

TypeError: asarray() got an unexpected keyword argument 'out'

**Comment by carterbox** [comment]
@XYangXRay, this repository is for managing distribution/packaging of dxchange, not for reporting bugs in the package itself. Please report this bug on the repository containing the dxchange source code: https://github.com/data-exchange/dxchange/issues
